spring:
  profiles: #  请保存为UTF-8格式
    active:
        - dev
# 分隔符，使得不同环境的配置在同一个文件中
---
#dev指开发环境
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-atguigu-dev
---
#test指测试环境
spring:
  profiles: test   
  application: 
    name: microservicecloud-config-atguigu-test
#请保存为UTF-8格式